services:
  postgres:
    image: postgres:16  
    container_name: my_postgres  
    restart: always  
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: studentdb 
    ports:
      - "5432:5432"  # Прокидываем порт PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:  # Объявляем том для хранения данных
