version: '3.8'

services:
  postgres:
    image: postgres:16  
    container_name: my_postgres  
    restart: always  
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: studentdb 
    ports:
      - "5432:5432"  # Прокидываем порт PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  # Сохраняем данные после выключения контейнера

  app:
    build: .
    container_name: my_spring_app
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/university
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
  postgres_data:  # Объявляем том для хранения данных
